services:
  ssh-alert:
    image: datamate/ssh-alert:latest
    container_name: ssh-alert
    restart: unless-stopped
    environment:
      - ALLOWED_IPS=${ALLOWED_IPS:?Variable is not set or empty}
      - ZAMMAD_URL=${ZAMMAD_URL:?Variable is not set or empty}
      - ZAMMAD_TOKEN=${ZAMMAD_TOKEN:?Variable is not set or empty}
      - ZAMMAD_TICKET_HOSTNAME=${ZAMMAD_TICKET_HOSTNAME:?Variable is not set or empty}
      - ZAMMAD_GROUP=${ZAMMAD_GROUP:-Support}
    volumes:
      - /var/log/auth.log:/var/log/auth.log:ro
